# Generated by Django 6.1.2 on 2026-10-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('aadhaar', models.FileField(upload_to='aadhaar/')),
            ],
        ),
    ]
